theme: jekyll-theme-midnight


# Site wide configuration
title: My diary...?
locale: en_US
logo: # filename of a logo image that has been placed into your images directory
# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Simone Ragoni
  avatar: images/28685072_1624565274264624_8263257815999232116_n.jpg
  bio: "I am still learning how to use this GitHub feature... Consider it more like a diary at the moment!"
  email: simone.ragoni@cern.ch
  # Do not include the @ symbol in your Twitter username
  # twitter: laderast
  linkedin: https://www.linkedin.com/in/simone-ragoni
  github: siragoni
  # orcid: # ID Number (ex. 0000-0000-0000-0000)
  researchgate: https://www.researchgate.net/profile/Simone_Ragoni
#   mendeley: #username
#   google:
#     plus: #username
#     analytics:
#     verify:
#     scholar: #id
